import type { VolumeComparisonCandidateEvidence } from "./volumeComparison";
import type { VolumeDifferenceInspection } from "./volumeDifferenceInspector";

export type DifferenceCandidateEvidencePanelProps = {
  evidence: VolumeComparisonCandidateEvidence;
  inspection: VolumeDifferenceInspection | null;
};

function OptionContributions({
  title,
  contributions,
}: {
  title: string;
  contributions:
    | VolumeDifferenceInspection["conditionA"]["voxel"]["optionContributions"]
    | undefined;
}) {
  return (
    <div className="difference-candidate-side">
      <strong>{title}</strong>
      {contributions?.length ? (
        <ol>
          {contributions.map((item) => (
            <li key={item.optionId}>
              <code>{item.optionId}</code>
              <span>
                {item.kind} · score {item.geometricScore.toFixed(4)} · local {" "}
                {item.localContribution.toFixed(4)}
              </span>
            </li>
          ))}
        </ol>
      ) : (
        <p>No retained candidate contribution at this inspected cell.</p>
      )}
    </div>
  );
}

export function DifferenceCandidateEvidencePanel({
  evidence,
  inspection,
}: DifferenceCandidateEvidencePanelProps) {
  if (evidence.mode === "state_only") {
    return (
      <article className="difference-candidate-evidence is-state-only">
        <p className="eyebrow">CANDIDATE EVIDENCE</p>
        <h2>State-only comparison</h2>
        <p>
          Candidate options are intentionally absent from both conditions. This
          preserves the v1.3 Future Space / Option Creation contract.
        </p>
        <code>included=false · regenerated=false · futureObservedFrames=false</code>
      </article>
    );
  }

  return (
    <article className="difference-candidate-evidence is-regenerated">
      <p className="eyebrow">REGENERATED CANDIDATE EVIDENCE</p>
      <div className="difference-candidate-provenance">
        <div>
          <span>Generator</span>
          <strong>
            {evidence.provenance.generatorName} · {evidence.provenance.packageVersion}
          </strong>
        </div>
        <div>
          <span>Config SHA-256</span>
          <code>{evidence.provenance.configSha256}</code>
        </div>
        <div>
          <span>Candidate support</span>
          <strong>
            {evidence.supportSummary.intersection} shared · {evidence.supportSummary.leftOnly}{" "}
            A-only · {evidence.supportSummary.rightOnly} B-only
          </strong>
        </div>
        <div>
          <span>Contracts</span>
          <code>
            {evidence.provenance.candidateIdentityContract} · {" "}
            {evidence.provenance.interventionContract}
          </code>
        </div>
      </div>
      <p>
        A uses the frozen authoritative showcase candidates. B uses candidates
        regenerated by Python AffordanceEngine from the matched earlier-run
        alternative frame. These are model-derived geometric scores, not observed
        availability labels or causal effects.
      </p>
      {inspection ? (
        <div className="difference-candidate-contributions">
          <OptionContributions
            title="Condition A local option contributions"
            contributions={inspection.conditionA.voxel?.optionContributions}
          />
          <OptionContributions
            title="Condition B local option contributions"
            contributions={inspection.conditionB.voxel?.optionContributions}
          />
        </div>
      ) : (
        <p>Inspect a retained cell to trace its A/B option contributions.</p>
      )}
    </article>
  );
}
